
# ========================================
# API ORDENS-SERVIÇO
# ========================================

### Buscar todas as OS's com (admin)
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025

### Buscar todas as OS's com (admin) e filtra por codCliente
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025&codClienteFilter=120

### Buscar todas as OS's com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025&codClienteFilter=120&codRecursoFilter=122

# ===============================================================================================================================================

# ========================================
# API HRS-CONTRATADAS-HRS-EXECUTADAS
# ========================================

### Buscar todas as OS's com (admin)
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025

### Buscar todas as OS's com (admin) e filtra por codCliente
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025&codClienteFilter=120

### Buscar todas as OS's com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025&codClienteFilter=120&codRecursoFilter=122


# ===============================================================================================================================================
